name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        env:
          SHIPPERAPIURL: ${{ secrets.SHIPPERAPIURL }}
          BIDDINGAPIURL: ${{ secrets.BIDDINGAPIURL }}
          BOOKINGAPIURL: ${{ secrets.BOOKINGAPIURL }}
          BUYGPSAPIURL: ${{ secrets.BUYGPSAPIURL }}
          DOCUMENTAPIURL: ${{ secrets.DOCUMENTAPIURL }}
          DRIVERAPIURL: ${{ secrets.DRIVERAPIURL }}
          GETUID: ${{ secrets.GETUID }}
          GETUIDBYMAIL: ${{ secrets.GETUIDBYMAIL }}
          GETUIDBYPHONENUMBER: ${{ secrets.GETUIDBYPHONENUMBER }}
          GPSAPIURL: ${{ secrets.GPSAPIURL }}
          IDFYACCOUNTID: ${{ secrets.IDFYACCOUNTID }}
          IDFYAPIKEY: ${{ secrets.IDFYAPIKEY }}
          IDFYKEY_ID: ${{ secrets.IDFYKEY_ID }}
          IDFYOU_ID: ${{ secrets.IDFYOU_ID }}
          IDFYSECRET_KEY: ${{ secrets.IDFYSECRET_KEY }}
          INSTALLERAPI: ${{ secrets.INSTALLERAPI }}
          LOADAPIURL: ${{ secrets.LOADAPIURL }}
          MAPKEY: ${{ secrets.MAPKEY }}
          MAPKEYNEW: ${{ secrets.MAPKEYNEW }}
          MAPKEYOLD: ${{ secrets.MAPKEYOLD }}
          ONESIGNALAPIKEY: ${{ secrets.ONESIGNALAPIKEY }}
          ONESIGNALAPPID: ${{ secrets.ONESIGNALAPPID }}
          PLACEAUTOCOMPLETEPROXY: ${{ secrets.PLACEAUTOCOMPLETEPROXY }}
          RAPIDKEY: ${{ secrets.RAPIDKEY }}
          ROUTEDATAAPIURL: ${{ secrets.ROUTEDATAAPIURL }}
          ROUTEHISTORYAPIURL: ${{ secrets.ROUTEHISTORYAPIURL }}
          SHAREURL: ${{ secrets.SHAREURL }}
          TRACCARAPI: ${{ secrets.TRACCARAPI }}
          TRACCARPASS: ${{ secrets.TRACCARPASS }}
          TRACCARUSER: ${{ secrets.TRACCARUSER }}
          TRANSPORTERAPIURL: ${{ secrets.TRANSPORTERAPIURL }}
          TRUCKAPIURL: ${{ secrets.TRUCKAPIURL }}
          UIDBYPHONENUMBER: ${{ secrets.UIDBYPHONENUMBER }}
          WEBHOOKURL: ${{ secrets.WEBHOOKURL }}
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIPPERWEBAPP }}'
          channelId: live
          projectId: shipperwebapp
